frontend/controllers/ClientController.php
<?php


namespace frontend\controllers;


use frontend\form\ClientCreateForm;
use frontend\form\ClientSearch;
use frontend\services\ClientService;
use Yii;
use yii\web\Controller;

class ClientController extends Controller
{
    private $service;

    public function __construct($id, $module, ClientService $service, $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->service = $service;
    }

    public function actionIndex()
    {
        $model = new ClientSearch();
        $dataProvider = $model->search(Yii::$app->request->queryParams);

        return $this->render('index', ['model'=>$model, 'dataProvider'=>$dataProvider]);
    }

    public function actionCreate()
    {
        $form = new ClientCreateForm();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $this->service->createClient($form);
                return $this->redirect(['index']);
            } catch (\DomainException $e) {
                Yii::$app->errorHandler->logException($e);
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }
        return $this->render('create', [
            'model' => $form,
        ]);
    }
}

frontend/controllers/DepositController.php
<?php


namespace frontend\controllers;


use frontend\form\ClientDepositSearch;
use frontend\form\ClientSearch;
use frontend\form\DepositCreateForm;
use frontend\services\DepositService;
use Yii;
use yii\web\Controller;

class DepositController extends Controller
{
    private $service;

    public function __construct($id, $module, DepositService $service, $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->service = $service;
    }
    public function actionIndex()
    {
        $model = new ClientDepositSearch();
        $dataProvider = $model->search(Yii::$app->request->queryParams);

        return $this->render('index', ['model'=>$model, 'dataProvider'=>$dataProvider]);
    }

    public function actionCreate()
    {
        $form = new DepositCreateForm();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $this->service->createDeposit($form);
                return $this->redirect(['index']);
            } catch (\DomainException $e) {
                Yii::$app->errorHandler->logException($e);
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }
        return $this->render('create', [
            'model' => $form,
        ]);
    }
}

frontend/controllers/HistoryController.php
<?php


namespace frontend\controllers;


use frontend\form\ClientDepositHistorySearch;
use Yii;
use yii\web\Controller;

class HistoryController extends Controller
{
    public function actionIndex()
    {
        $model = new ClientDepositHistorySearch();
        $dataProvider = $model->search(Yii::$app->request->queryParams);

        return $this->render('index', ['model'=>$model, 'dataProvider'=>$dataProvider]);
    }
}

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Clients', 'url' => ['/client/index']],
        ['label' => 'Deposits', 'url' => ['/deposit/index']],
        ['label' => 'History', 'url' => ['/history/index']],
    ];
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>